server {
    listen 80;
    server_name notdone.dev;
    return 301 https://apps.notdone.dev$request_uri;
}

server {
    listen 80 default_server;
    server_name apps.notdone.dev;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(html)$ {
        add_header Cache-Control "no-cache, must-revalidate";
    }
}
